Added P4runtime Rules for Service
ipdk-io/k8s-infra-offload-old pull request #12
Opened 2022-11-09 07:20 UTC by vishala-r

Signed-off-by: Vishalakshi <vishalakshi.r@intel.com>

2022-11-09 11:43 UTC, ahalimx86 commented on pkg/inframanager/p4/service.go
> +func WriteDestIpTable(ctx context.Context, p4RtC *client.Client, podIpAddr []string, podMacAddr []string, portID []uint32, modBlobPtrDnat []uint32, flag bool) error {
Suggestion: it would be good idea to rename `flag` to `isDelete` or something similar.

2022-11-09 11:58 UTC, ahalimx86 commented on pkg/inframanager/p4/service.go
> +	if flag == true {
nit: checking `== true` is redundant

2022-11-09 12:23 UTC, ahalimx86 commented on pkg/inframanager/p4/service.go
> +		return nil
If we encounter errors on a specific table update, this method will return from here and this will result in partial tables update. How are you going to handle this situation?
Are these table update action idempotent?

2022-11-09 20:23 UTC, dhruvpt requested changes
We should not commit this change until the P4 pipeline (k8s_dp.p4) has been updated with all required tables.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +				log.Errorf("Invalid mac address")
In the error log, we should print the err and the invalid MAC string parameterm that failed to parse?
Same comment applies to similar parsing functions below.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +				err = fmt.Errorf("Invalid IP address")
The err returned here should be the one returned by ParseIP function. And, in the error message, print that err and the invalid IP address string parameter.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +func WriteDestIpTable(ctx context.Context, p4RtC *client.Client, podIpAddr []string, podMacAddr []string, portID []uint32, modBlobPtrDnat []uint32, flag bool) error {
We can name it as "addEntry" because, when this boolean is true, we are adding entry.
Same comment for other similar functions below.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +func TxBalanceTcpTable(ctx context.Context, p4RtC *client.Client, serviceIpAddr string, servicePort uint32, groupID uint32, flag bool) error {
The servicePort can be uint16 otherwise, we have to check whether it is within range or not.
same comment applies in other functions below that take L4 port as uint32 parameter

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +func AsSl3UdpTable(ctx context.Context, p4RtC *client.Client, memberID []uint32, modBlobPtr []uint32, groupID uint32, flag bool) error {
This function is almost identical to above function with only table name changing from _tcp to _udp. Going forward, we should consider combinding the two into one function and having protocol as a parameter to differentiate. That would avoid these almost-duplicate functions.
Same comment applies to TX Balance tables below.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +	if flag == true {
The if-else blocks can be made smaller by pulling out all the common code viz parsing parameters and building the input entry key. Within if-else, we just need to conditionally set action and call the appropriate p4Rtc function to add or delete the entry.

2022-11-09 20:23 UTC, dhruvpt commented on pkg/inframanager/p4/service.go
> +		return nil
I agree. Upon error, we need to undo the previous successful operations.
Same comment applies to all such functions where we have multiple sub operations.

2022-11-09 22:20 UTC, venkateshpnv commented on pkg/inframanager/p4/service.go
> +func WriteDestIpTable(ctx context.Context, p4RtC *client.Client, podIpAddr []string, podMacAddr []string, portID []uint32, modBlobPtrDnat []uint32, flag bool) error {
Can you change the function name to UpdateDestIpTable(). I believe the same is applicable for other functions too as they perform both insertion and deletion of the entries based on the flag.

2022-11-09 22:20 UTC, venkateshpnv commented on pkg/inframanager/p4/service.go
> +var groupIDTracker *groupIDCollection
How is it different from the service story entry? How will it be updated with the entries if the inframanager pod restarts?

2022-11-10 06:02 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +func WriteDestIpTable(ctx context.Context, p4RtC *client.Client, podIpAddr []string, podMacAddr []string, portID []uint32, modBlobPtrDnat []uint32, flag bool) error {
ok. done, will do this change

2022-11-10 06:02 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +	if flag == true {
will do

2022-11-10 06:02 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +		return nil
yes, we will commit rollback mechanism as well

2022-11-10 06:04 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +				log.Errorf("Invalid mac address")
yes. will do

2022-11-10 06:05 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +				err = fmt.Errorf("Invalid IP address")
ParseIP doesn't return error. upon successful parsing it returns ip address otherwise it return nil

2022-11-10 06:10 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +func TxBalanceTcpTable(ctx context.Context, p4RtC *client.Client, serviceIpAddr string, servicePort uint32, groupID uint32, flag bool) error {
i didn't understand this comment. what range are you mentioning here? i think only node ports have range right?

2022-11-10 06:34 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +func AsSl3UdpTable(ctx context.Context, p4RtC *client.Client, memberID []uint32, modBlobPtr []uint32, groupID uint32, flag bool) error {
ya..i understand. but i did like this to resonate with the p4 program we have. because we are having different tables AsSl3Udp and AsSl3Tcp, i created 2 functions to program each. i am following the same pattern for cni add too. so to keep consistent wit that, i created 2 different functions

2022-11-10 06:43 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +func WriteDestIpTable(ctx context.Context, p4RtC *client.Client, podIpAddr []string, podMacAddr []string, portID []uint32, modBlobPtrDnat []uint32, flag bool) error {
i have kept function names same as the table name we are using in p4 program.

2022-11-10 06:46 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +var groupIDTracker *groupIDCollection
ya. good suggestion. i will use store API to get the group id.

2022-11-10 10:09 UTC, closed without merging

2022-11-10 10:09 UTC, vishala-r commented
will come back with roll back mechanism and other enhancements