Updated README for running ping with ARP proxy
ipdk-io/k8s-infra-offload-old pull request #20
Opened 2022-11-17 17:49 UTC by dhruvpt

2022-11-18 09:00 UTC, vishala-r requested changes

2022-11-18 09:00 UTC, vishala-r commented on README.md
> +  ip link set P4TAP_0 name TAP0
is this tested after renaming? does it work? because, in code we are actually extracting port ID from interface name based on '_' delimiter while create network call, to configure forwarding tables. so i think its better to either rename it to TAP_0 or keep it as P4TAP_0.

2022-11-18 09:00 UTC, vishala-r commented on README.md
> +  To run a simple ping test from one pod to another, create two test pods as below. Note that, before creating the second test pod, edit the test_pod.yaml file to configure a different name (test-pod
may be its better to illustrate with sample example where to change the names

2022-11-18 13:32 UTC, dhruvpt commented on README.md
> +  ip link set P4TAP_0 name TAP0
Yes, it works and is much simpler to keep the interface out of agent's pool of interfaces.
Note that, this renamed interface is not to be used by Infra-agent/infra-manager for pods. And, instead of moving into a namespace, it can just be renamed providing same obscurity.

2022-11-18 13:34 UTC, dhruvpt commented on README.md
> +  To run a simple ping test from one pod to another, create two test pods as below. Note that, before creating the second test pod, edit the test_pod.yaml file to configure a different name (test-pod
ok

2022-11-18 22:05 UTC, nupurjai approved these changes

2022-11-18 22:08 UTC, nupurjai commented
New changes for service and arp_proxy look good.

2022-11-18 22:13 UTC, venkateshpnv approved these changes

2022-11-19 03:37 UTC, vishala-r approved these changes

2022-11-19 03:38 UTC, merged