Support update requests for NatTranslationAdd.
ipdk-io/k8s-infra-offload-old pull request #24
Opened 2022-11-23 08:23 UTC by venkateshpnv

Signed-off-by: Venkatesh Petla <neelakanta.venkatesh.petla@intel.com>

2022-12-13 02:18 UTC, nupurjai commented on inframanager/api_handler/api_handler.go
> +	if numEps == 0 {
This should come right after check is done at line 441

2022-12-14 19:22 UTC, vishala-r requested changes

2022-12-14 19:22 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		podMacAddrs, podPortIDs, serviceIpAddr, serviceMacAddr,
according to the new p4, we are not using macs for programming service tables.

2022-12-14 19:22 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		podMacAddrs, podPortIDs, serviceIpAddr, serviceMacAddr,
and servicemac too

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +		if action != Update {
inside txbalancetcp() function, we are anyway checking if action is  update, then we do nothing. so do we need this condition here?

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +		if action != Update {
same thing. in tcbalanceudp() function, we are checking if case action is update. if update, then we do nothing. so this condition is redundant.

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +	if action != Update {
same comment as above

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +func properKey(s Service) bool {
please make these caps. otherwise we can't access it from package outside of store.

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +func getKey(s Service) (key string, ok bool) {
better to make it in caps: Getkey()

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +	if len(s.ClusterProto) == 0 {
are you sure if k8s always sends cluster port in NAT add translation call?

2022-12-14 19:22 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +	if s.ClusterPort < 0 {
instead of less than 0, should we check for actual port range here? because s.ClusterPort is uint32 here.

2022-12-14 19:22 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		if utils.IsIn(ipAddr, serviceEpIpAddrs) {
lets consider case, where, 1st nat translation add() comes with 4 backend pods, 2nd  nat translation add() forthe same cluster ip, comes with only 3 backend pod? 1 backend pod got deleted. then update should take care of that too right? it should delete the rules corresponding to the deleted backend pod right? is it being handled in this PR?

2022-12-14 19:24 UTC, closed without merging

2022-12-14 19:25 UTC, venkateshpnv commented
This PR has DCO issues which could not be resolved. Replicated the changes in another PR https://github.com/ipdk-io/k8s-infra-offload/pull/51