Get port id from the interface name.
ipdk-io/k8s-infra-offload-old pull request #26
Opened 2022-11-25 22:11 UTC by venkateshpnv

In the CNI add API, the current implementation fetches the port id of the interface from its name. It assumes the name has the port id is part of the interface name as a standard expression. This implementation is not reliable in case the dpdk assigns a different port id for the interface.

Make it more dynamic and always fetch the port id by sending a get request to the gNMI server.

Signed-off-by: Venkatesh Petla <neelakanta.venkatesh.petla@intel.com>

2022-11-26 07:27 UTC, vishala-r requested changes

2022-11-26 07:27 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +func CloseGNMIConn() {
aren't we supposed to take care of tomb thing here? for gnmi connection?

2022-11-26 07:27 UTC, vishala-r commented on inframanager/cmd/main.go
> +			api.CloseP4RtCCon()
here also, we need to add api.CloseGNMIConn(), because we won't go forward if set forward pipe fails

2022-11-26 07:27 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +	pb "github.com/ipdk-io/k8s-infra-offload/proto"
can we rename this as gnmi proto. because we have multiple protos in our repo, to avoid confusion, better to rename it to gnmiproto?

2022-11-26 19:35 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +	pb "github.com/ipdk-io/k8s-infra-offload/proto"
proto is the common package of all protobuf implementations. It includes both infraagent and inframanager gRPC definitions and pb files.

2022-11-26 19:48 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +func CloseGNMIConn() {
tomb is required for the gRPC server implementation. Here we are opening a client connection to the gNMI server. We generally don't use tomb for clients.

2022-11-26 19:50 UTC, venkateshpnv commented on inframanager/cmd/main.go
> +			api.CloseP4RtCCon()
Yeah. Will do.

2022-11-28 07:29 UTC, vishala-r approved these changes
looks good to me

2022-11-28 16:50 UTC, ahalimx86 commented on inframanager/api_handler/api_handler.go
> +		return
You should return error from here. Only `return` will return `zero` values for both portID and error here. And this will be treated as valid output by caller.

2022-11-28 16:57 UTC, ahalimx86 commented on inframanager/api_handler/api_handler.go
> +	req := pb.GetRequest{}
The `req` should just be a pointer to pb.GetRequest{}. And the all the subsequent fields that you are assigning could be just initialized at the same time.

2022-11-28 17:01 UTC, ahalimx86 commented on inframanager/api_handler/api_handler.go
> +	return
Avoid using implicit return statements. This can lead to hard to debug errors if the variables scope changes somehow.

2022-11-28 22:06 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +		return
The err is updated with the proper error information before returning from the call. If the status is an error, the caller will not use the portID irrespective of its value. So, zero value for portID should not be a problem.

2022-11-28 22:06 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +	req := pb.GetRequest{}
Committed the required changes. Please check.

2022-11-28 22:08 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +	return
I have declared the return variables as part of the function signature. So, their scope should be extended till the end of the function. I believe it should not be an issue unless there are implementation errors.

2022-12-02 03:02 UTC, dhruvpt approved these changes

2022-12-05 16:35 UTC, nupurjai approved these changes

2022-12-05 22:11 UTC, nupurjai approved these changes

2022-12-05 22:37 UTC, nupurjai approved these changes

2022-12-05 22:42 UTC, nupurjai approved these changes

2022-12-05 23:25 UTC, nupurjai approved these changes

2022-12-05 23:29 UTC, nupurjai approved these changes

2022-12-05 23:30 UTC, merged