Add rule for host IP
ipdk-io/k8s-infra-offload-old pull request #42
Opened 2022-12-08 02:45 UTC by venkateshpnv

Add a rule to the dpdk pipeline for forwarding the packets to/from host IP. Forward them via the default host interface and its port id.

How to get the host IP from the inframanager pod?
Kubernetes populates the pod object in the apiserver with spec:
nodeName: node1
status:
podIP: 172.168.0.2
hostIP: 192.168.0.1

Here hostIP is the nodeIP on which the pod is running on.

Inside the inframanager pod, read the node IP from the pod object and use it for programming the forwarding rules.

Signed-off-by: Venkatesh Petla <neelakanta.venkatesh.petla@intel.com>

2022-12-08 07:13 UTC, nupurjai approved these changes

2022-12-08 07:45 UTC, vishala-r approved these changes

2022-12-08 08:25 UTC, lpawlikx requested changes

2022-12-08 08:25 UTC, lpawlikx commented on pkg/utils/utils.go
> +
Please do not add more functionality to this package, it has already more than it should. Created another more related utils go source file ie. env_untils.go Also you do not add tests for new functionality.

2022-12-08 08:25 UTC, lpawlikx commented on pkg/utils/utils.go
> +func UNUSED(x ...interface{}) {}
What is this ?

2022-12-08 08:32 UTC, vishala-r requested changes

2022-12-08 08:32 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +	IP, netIp, err := net.ParseCIDR(types.DefaultRoute)
instead of using UNUSED(), we can just not declare that variable. IP,_,err:=net.ParseCIDR()

2022-12-08 09:04 UTC, lpawlikx commented on inframanager/api_handler/api_handler.go
> +	utils.UNUSED(netIp)
OMG ! This is not how we do it ! https://go.dev/doc/effective_go#blank

2022-12-08 10:13 UTC, lpawlikx commented on deploy/inframanager-daemonset.yaml
> +        env:
Maybe this is not the best approach to obtain this information. Agent could send that info in SetupHostInterface

2022-12-09 00:18 UTC, venkateshpnv commented on pkg/utils/utils.go
> +func UNUSED(x ...interface{}) {}
It's a dummy function to overcome checkmarx/coverity issues as part of SDLe. In case we don't use the return values of a function, using '_' raises checkmarx errors. So, we get the data and pass them to UNUSED() 
for example: 
IP, _, err := net.ParseCIDR(types.DefaultRoute)
raises the checkmarx error.

So, call
IP, netIp, err := net.ParseCIDR(types.DefaultRoute)
and UNUSED(netIp)

2022-12-09 00:19 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +	IP, netIp, err := net.ParseCIDR(types.DefaultRoute)
Explained in the above reply to lukasz comment. Please check.

2022-12-09 00:20 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +	utils.UNUSED(netIp)
Explained in the above comment. Please check.

2022-12-09 00:29 UTC, venkateshpnv commented on pkg/utils/utils.go
> +
Sure. Will move them to another file.

2022-12-09 00:32 UTC, venkateshpnv commented on deploy/inframanager-daemonset.yaml
> +        env:
We don't get the node IP from the SetupHostInterface request. It only provides the host interface IP information as shown below.

 time="2022-12-08T02:36:46Z" level=info msg="Incoming SetupHostInterface request if_name:\"P4TAP_0\" ipv4_addr:\"172.168.0.2/24\" mac_addr:\"46:6d:c     9:80:7b:95\" " func="github.com/ipdk-io/k8s-infra-offload/inframanager/api_handler.(*ApiServer).SetupHostInterface" file="/workspace/inframanager/a     pi_handler/api_handler.go:718" fields.func=SetupHostInterface func="github.com/ipdk-io/k8s-infra-offload/inframanager/api_handler.(*ApiServer).Setu     pHostInterface" pkg=inframanager

We are getting the node ip directly from the apiserver's pod object. I believe this is a standard way.  Please check the below link

https://wangwei1237.github.io/Kubernetes-in-Action-Second-Edition/docs/Passing_pod_metadata_to_the_application_via_the_Downward_API.html

Also, the infraagent gets the node IP from the pod object
        env:
  ┆ ┆ ┆ - name: NODE_NAME
  ┆ ┆ ┆ ┆ valueFrom:
  ┆ ┆ ┆ ┆ ┆ fieldRef:
  ┆ ┆ ┆ ┆ ┆ ┆ fieldPath: spec.nodeName

2022-12-09 06:00 UTC, nupurjai approved these changes

2022-12-09 06:02 UTC, vishala-r approved these changes

2022-12-09 06:37 UTC, lpawlikx commented on pkg/utils/utils.go
> +func UNUSED(x ...interface{}) {}
Can I see this error ? I clearly do not understand how this is an error. It is a common practice to use blank operator and not this. I think we can ignore this report.

2022-12-09 06:39 UTC, lpawlikx commented on deploy/inframanager-daemonset.yaml
> +        env:
Yes it is a standard way if you deploy deamonset on cluster. Do you think it will work when you start manager outside of cluster (i.e. NIC)

2022-12-09 06:44 UTC, lpawlikx commented on deploy/inframanager-daemonset.yaml
> +        env:
And yes this information is not in SetupHostInterface we nee to add it.

2022-12-09 06:50 UTC, lpawlikx commented on inframanager/api_handler/api_handler.go
> +	IP, netIp, err := net.ParseCIDR(types.DefaultRoute)
Why do you use uppercase letter for variable ? It has no effect in function body but it looks odd.

2022-12-09 16:21 UTC, venkateshpnv commented on deploy/inframanager-daemonset.yaml
> +        env:
Do you mean running as a binary and not as a pod? In that case, we should set the env NODE_IP.

2022-12-09 16:24 UTC, venkateshpnv commented on pkg/utils/utils.go
> +func UNUSED(x ...interface{}) {}
We don't have the latest report. I had sent an email with infra-agent Checkmarx errors last week.  Please check.

2022-12-09 16:26 UTC, venkateshpnv commented on deploy/inframanager-daemonset.yaml
> +        env:
If you are planning to add the node IP as part of the SetupHostInterface, please let us know once it is done. We will use it instead of the status.HostIP

2022-12-09 16:28 UTC, nupurjai commented
For now, with the comments addressed for not handled variable. I will merge it. We will address further changes as a part of future PR. @lpawlikx, will that be fine. I need this functionality to bring the cluster up.

2022-12-09 16:28 UTC, merged