Initial P4 code to support network policies
ipdk-io/k8s-infra-offload-old pull request #44
Opened 2022-12-09 19:40 UTC by dhruvpt

Signed-off-by: Tripathi, Dhruv Prakash <dhruv.tripathi@intel.com>

2022-12-12 16:59 UTC, shweta503 requested changes

2022-12-12 16:59 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +            key = {
We decided to have two SEM tables - acl_srcip_proto_table and acl_srcip_table. The latter would match only on the src ip address to take care of the scenario where only ipset is specified in the rule and not protocol (and port range). The "ipset only" scenario is not handled by having just this table.

2022-12-12 16:59 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +        table acl_dstip_proto_table {
Same as above comment

2022-12-12 16:59 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +                {
The order of applying DNAT and egress policy seems wrong here. In TX direction (HOST_TO_NET), we apply egress policy *after* load balancing/DNAT.

2022-12-12 16:59 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +                {
Again the order seems wrong. I believe, the correct order of the apply block should be:
1. If (RX), apply ingress policy
2. Load balance/DNAT or SNAT
3. If (TX), apply egress policy

2022-12-12 17:50 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +            key = {
In both these tables, the second protocol field is LPM and thus, can be completely wildcarded to have L4 protocol independent policy.

2022-12-12 17:54 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +                {
The egress policy is w.r.t. to source/originating pod and destination network. The destination network can be cluster IP address to filter access to a service without having to add individual rules for all end points. That requires filtering before DNAT. This is esp. helpful when end points can change dynamically. Let's talk further on this.

2022-12-12 18:00 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +                {
We are here assuming only pod-to-pod traffic at present. So, any processing begins with egress filter for originating pod (which can be client or a service end-point). Thereafter, after DNAT (or SNAT), packet is looped back to re-enter as ingress traffic. At this point, all packet modifications have already been done and only thing remaining is the ingress filtering w.r.t. destination pod (which can be client pod or a service end-point). The remote IP, for filtering purpose, can now be cluster IP as well. Again, let's talk further on this.

2022-12-12 23:46 UTC, shweta503 approved these changes

2022-12-12 23:46 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +                {
I see the change from exact to lpm. thanks.

2022-12-12 23:46 UTC, shweta503 commented on k8s_dp/k8s_dp.p4
> +                {
Yes, with change in design from applying policy post-DNAT to pre-DNAT, this makes sense.

2022-12-13 16:58 UTC, nupurjai commented on k8s_dp/k8s_dp.p4
> +const RangeCheckRefType_t CHECK_UDPL_DST_PORT_RANGE = (RangeCheckRefType_t) 4;
For UDPL, we need checksum checks. Parser is not doing it right now.

2022-12-13 17:00 UTC, nupurjai commented on k8s_dp/k8s_dp.p4
> +            P_cntr.count(ACL_DENIED);
keep it lowercase.

2022-12-13 17:38 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +const RangeCheckRefType_t CHECK_UDPL_DST_PORT_RANGE = (RangeCheckRefType_t) 4;
I assume that's a general comment as in this commit for policy, we are not doing anything related to checksum of any type.

2022-12-13 17:40 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +            P_cntr.count(ACL_DENIED);
I assume, you are referring to P_cntr

2022-12-13 19:24 UTC, closed without merging

2022-12-13 19:31 UTC, jokuniew commented on README.md
> +  ip netns exec arpns ARP_PROXY_IF=P4TAP_0 ./bin/arp_proxy &
This line keeps telling me that `exec of "ARP_PROXY_IF=P4TAP_0" failed: No such file or directory`
When I do `ip netns exec arpns ls ./bin` I can see the arp_proxy binary

It used to work on previous version. Shouldn't be there any more changes done?

2022-12-14 05:13 UTC, nupurjai commented on README.md
> +  ip netns exec arpns ARP_PROXY_IF=P4TAP_0 ./bin/arp_proxy &
ip netns exec arpns export ARP_PROXY_IF=P4TAP_0 && ./bin/aprp_proxy &