Support update for NatTranslateAdd
ipdk-io/k8s-infra-offload-old pull request #51
Opened 2022-12-14 18:12 UTC by venkateshpnv

Signed-off-by: Venkatesh Petla <neelakanta.venkatesh.petla@intel.com>

2022-12-14 19:31 UTC, vishala-r requested changes

2022-12-14 19:31 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		podMacAddrs, podPortIDs, serviceIpAddr, serviceMacAddr,
according to new p4, we are not using podmacaddrs for configuring service tables.

2022-12-14 19:31 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		podMacAddrs, podPortIDs, serviceIpAddr, serviceMacAddr,
and servicemac too

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +		if action != Update {
inside txbalancetcp() function, we are anyway checking if action is update, then we do nothing. so do we need this condition here?

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +		if action != Update {
same thing. in tcbalanceudp() function, we are checking if case action is update. if update, then we do nothing. so this condition is redundant.

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/p4/service.go
> +	if action != Update {
same comment as above

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +func properKey(s Service) bool {
please make these caps. otherwise we can't access it from package outside of store. ProperKey()

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +func getKey(s Service) (key string, ok bool) {
GetKey()

2022-12-14 19:31 UTC, vishala-r commented on pkg/inframanager/store/storeservice.go
> +	if s.ClusterPort < 0 {
does nat translation add call always send cluster port?
also, its better to check for port range here, instead of <0. because s.ClusterPort is uint32

2022-12-14 19:31 UTC, vishala-r commented on inframanager/api_handler/api_handler.go
> +		if utils.IsIn(ipAddr, serviceEpIpAddrs) {
lets consider case, where, 1st nat translation add() comes with 4 backend pods, 2nd nat translation add() forthe same cluster ip, comes with only 3 backend pod? 1 backend pod got deleted. then update should take care of that too right? it should delete the rules corresponding to the deleted backend pod right? is it being handled in this PR?

2022-12-14 19:56 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +		podMacAddrs, podPortIDs, serviceIpAddr, serviceMacAddr,
Ok. Will take a look

2022-12-14 19:59 UTC, venkateshpnv commented on pkg/inframanager/p4/service.go
> +		if action != Update {
This is the entry level check. Inside txbalancetcp(), we handle the case only after creating the data structures for match interface and table entries. Checking and skipping here will save time for executing those steps. And the check inside the txbalancetcp() is an internal check. In case, the callers calls it anyway.

2022-12-14 19:59 UTC, venkateshpnv commented on pkg/inframanager/p4/service.go
> +		if action != Update {
Same as explained in the above comment.

2022-12-14 19:59 UTC, venkateshpnv commented on pkg/inframanager/p4/service.go
> +	if action != Update {
Same as explained in the above comment.

2022-12-14 20:02 UTC, venkateshpnv commented on pkg/inframanager/store/storeservice.go
> +func properKey(s Service) bool {
I think, use of this function outside the store might not be required. We are using the key to read/write/delete from the store and those implementations are part of the store package. So, I believe we need the sanity checks for the key only inside the store package.
The outside packages will call read/write/delete functions.

2022-12-14 20:02 UTC, venkateshpnv commented on pkg/inframanager/store/storeservice.go
> +func getKey(s Service) (key string, ok bool) {
Same here.

2022-12-14 20:04 UTC, venkateshpnv commented on pkg/inframanager/store/storeservice.go
> +	if s.ClusterPort < 0 {
Yes. The NatTranslationAdd protobuf's input request provides us the protocol information. 
And sure. I will add changes to check the port range (0-65536).

2022-12-14 20:04 UTC, dhruvpt commented on inframanager/api_handler/api_handler.go
> +		if !service.UpdateToStore() {
Upon failure to add to store, should we not revert back the entry added earlier?
Same comment for below else case.

2022-12-14 20:04 UTC, dhruvpt commented on inframanager/api_handler/api_handler.go
> +		service.NumEndPoints = 0
why is numEndPoints 0? Shouldn't it be initialized to in.Backends?
Is this an unused element?

2022-12-14 20:07 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +		if utils.IsIn(ipAddr, serviceEpIpAddrs) {
Correct. We had the same question. The NPG team said that they will issue a NatTranslateDelete and NatTranslateAdd incase of backend deletions. I will confirm with them once again.

2022-12-14 20:34 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +		if !service.UpdateToStore() {
Yes. It needs to be reverted. Will add the changes.

2022-12-14 20:36 UTC, venkateshpnv commented on inframanager/api_handler/api_handler.go
> +		service.NumEndPoints = 0
It will be updated in the service.go file with the actual number of backends.

2022-12-19 20:19 UTC, nupurjai approved these changes

2022-12-19 20:26 UTC, vishala-r approved these changes

2022-12-19 22:38 UTC, nupurjai commented on pkg/inframanager/store/storedefinition.go
> +	MacAddr         string
Cleanup later. No MAC needed.

2022-12-19 22:40 UTC, nupurjai approved these changes

2022-12-19 22:46 UTC, nupurjai approved these changes

2022-12-19 22:50 UTC, shweta503 commented on pkg/inframanager/p4/service.go
> +	case Insert, Update:
Is the "Update" case updating an existing entry? If that's the case, shouldn't the old entry be deleted first? 
Same for all the tables that support "Update".

2022-12-19 22:50 UTC, shweta503 commented on pkg/inframanager/p4/service.go
> +	case Update:
Why is 'Update' supported for some tables but not others? 
If it's not supported, we should at least print a debug message before returning.

2022-12-19 23:44 UTC, shweta503 approved these changes

2022-12-20 00:08 UTC, merged