handle errors from health check watcher error channel
ipdk-io/k8s-infra-offload-old pull request #61
Opened 2023-01-06 11:53 UTC by ahalimx86

This fixes the coverity scan issue on error checking on error channel from health check watcher.

Signed-off-by: Abdul Halim <abdul.halim@intel.com>

2023-01-06 15:09 UTC, dhruvpt commented on pkg/utils/watcher.go
> +				return fmt.Errorf("watcher received error: %v", err)
Shouldn't we return explicit error code?

2023-01-06 15:30 UTC, ahalimx86 commented on pkg/utils/watcher.go
> +				return fmt.Errorf("watcher received error: %v", err)
There is no error code. This error channel is used as signal for watcher threads to return in the event of any error encounter during grpc health check.

2023-01-06 19:12 UTC, dhruvpt approved these changes

2023-01-06 21:00 UTC, nupurjai requested changes
Test is failing with this. Check the runner errors.

2023-01-11 10:09 UTC, ahalimx86 commented
> Test is failing with this. Check the runner errors.

fixed unit tests

2023-01-11 18:54 UTC, venkateshpnv approved these changes

2023-01-11 19:02 UTC, merged