updated codeowners file based on ownership
ipdk-io/k8s-infra-offload-old pull request #8
Opened 2022-11-07 13:40 UTC by mgaravin

2022-11-08 09:13 UTC, ahalimx86 commented on .github/CODEOWNERS
> +.github/workflows/*       @nupurjai @vishala-r @ahalimx86 @lpawlikx @ipatrykx @mgaravin
Can you please append @Eoghan1232 in the "Shared" and "Cloud Native" section please?

2022-11-08 09:47 UTC, mgaravin commented on .github/CODEOWNERS
> +.github/workflows/*       @nupurjai @vishala-r @ahalimx86 @lpawlikx @ipatrykx @mgaravin
updated

2022-11-08 10:03 UTC, Eoghan1232 approved these changes

2022-11-08 11:14 UTC, ahalimx86 approved these changes

2022-11-08 17:16 UTC, nupurjai reviewed
Can we please add venkateshpnv & dhruvpt as well to our side of code

2022-11-09 06:47 UTC, nupurjai approved these changes

2022-11-09 06:49 UTC, merged

2022-11-09 13:19 UTC, paulfhncw requested changes

2022-11-09 13:19 UTC, paulfhncw commented on .github/CODEOWNERS
> +# Cloud Native
please add @paulfhncw to the code owners for cloud native files